In [1]:
city_name = "City A"
print(f"City name: {city_name}")

City name: City A


In [2]:
x, y, z, a = 1, 2, 3

ValueError: not enough values to unpack (expected 4, got 3)

In [4]:
a = 2 + 3j
b = 1 -7j
print(a * b)

(23-11j)


In [14]:
x = "b"
id(x)

140719685718272

In [13]:
y = 11
id(y)

140719685683960

In [11]:
id(32768)

2709293033136

In [17]:
x1 = "Karmant"
id(x1)

2709289118784

In [18]:
x = "Karmanu"
id(x) - id(x1)

-1324896

In [19]:
def calculate_carbon_footprint(energy_consumption, emission_factor):
    """
    This function calculates the carbon footprint based on energy consumption 
    (in kilowatt-hours) and the emission factor (in kg CO2 per kWh).
    """
    return energy_consumption * emission_factor

In [20]:
# Example usage:
energy_consumption = 1000  # in kWh
emission_factor = 0.475      # kg CO2 per kWh

carbon_footprint = calculate_carbon_footprint(energy_consumption, emission_factor)
print(f"Carbon Footprint: {carbon_footprint} kg CO2")

#This will calculate and print the carbon footprint for the given energy consumption and emission factor.

Carbon Footprint: 475.0 kg CO2


In [21]:
# List of cities with their carbon footprints in tons CO2 per month
cities = [
    {"name": "City A", "carbon_footprint": 500},
    {"name": "City B", "carbon_footprint": 350},
    {"name": "City C", "carbon_footprint": 600},
    {"name": "City D", "carbon_footprint": 200},
]

# Lambda function to filter cities below the threshold (400 ton CO2)
sustainability_threshold = 400
sustainable_cities = list(filter(lambda city: city["carbon_footprint"] < sustainability_threshold, cities))

# Printing the filtered list of sustainable cities
print("Sustainable Cities:")
for city in sustainable_cities:
    print(city["name"])

Sustainable Cities:
City B
City D


In [25]:
a = ['apple']
a.append(123,123)
a

TypeError: list.append() takes exactly one argument (2 given)

In [47]:
import numpy as np
arr = np.array([[[[1, 2, 3],[4,5,6]],[[7,8,9],[10,11,12]]]])

In [48]:
print(arr.ndim)
print(arr.shape)

4
(1, 2, 2, 3)


In [49]:
print(arr)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
